ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER 사용자아이디 IDENTIFIED BY 비밀번호;
ALTER USER 사용자아이디 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER 사용자아이디 TEMPORARY TABLESPACE temp;
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO 사용자아이디;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO 사용자아이디;

COMMIT;
